# Generated by Django 5.0.4 on 2024-04-30 01:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_bedrock'),
    ]

    operations = [
        migrations.AddField(
            model_name='jars',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
