# Generated by Django 5.0.4 on 2024-04-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_jars_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='jars',
            name='title',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
    ]
