# Generated by Django 5.0.4 on 2024-04-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_jars_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jars',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='jars',
            name='posted',
            field=models.BooleanField(default=True),
        ),
    ]
