# Generated by Django 5.0.4 on 2024-04-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_jars_file_jars_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jars',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
