# Generated by Django 5.0.6 on 2024-05-16 23:18

import django.db.models.deletion
import manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50)),
                ('software', models.CharField(choices=[('Servers', 'Servers'), ('Proxies', 'Proxies'), ('Modded', 'Modded'), ('Vanilla', 'Vanilla'), ('Bedrock', 'Bedrock'), ('Misc', 'Misc')], max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('project', models.CharField(choices=[('Vanilla', 'Vanilla'), ('Paper', 'Servers'), ('Purpur', 'Servers'), ('Purformance', 'Servers'), ('Spigot', 'Servers'), ('CraftBukkit', 'Servers'), ('Tuinity', 'Proxies'), ('Airplane', 'Servers'), ('Folia', 'Servers'), ('SpongeVanilla', 'Modded'), ('Glowstone', 'Servers'), ('Fabric', 'Modded'), ('Forge', 'Modded'), ('Crucible', 'Misc'), ('Cardboard', 'Misc'), ('Arclight', 'Misc'), ('Mohist', 'Misc'), ('Magma', 'Misc'), ('SpongeForge', 'Misc'), ('Waterfall', 'Proxies'), ('Velocity', 'Proxies'), ('Bungeecord', 'Proxies'), ('Travertine', 'Proxies')], max_length=50)),
                ('buildnum', models.IntegerField(default=0)),
                ('posted', models.BooleanField(default=True)),
                ('experimental', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to=manager.models.get_upload_to)),
                ('file_size', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Jars',
            },
        ),
        migrations.CreateModel(
            name='bedrock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bedrock', to='manager.jar')),
            ],
            options={
                'verbose_name_plural': 'bedrock',
            },
        ),
        migrations.CreateModel(
            name='modded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Modded', to='manager.jar')),
            ],
            options={
                'verbose_name_plural': 'modded',
            },
        ),
        migrations.CreateModel(
            name='other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Misc', to='manager.jar')),
            ],
            options={
                'verbose_name_plural': 'misc',
            },
        ),
        migrations.CreateModel(
            name='proxies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Proxy', to='manager.jar')),
            ],
            options={
                'verbose_name_plural': 'proxies',
            },
        ),
        migrations.CreateModel(
            name='servers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Server', to='manager.jar')),
            ],
            options={
                'verbose_name_plural': 'servers',
            },
        ),
        migrations.CreateModel(
            name='vanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vanilla', to='manager.jar')),
            ],
            options={
                'verbose_name_plural': 'vanilla',
            },
        ),
    ]
