# Generated by Django 5.0.4 on 2024-04-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_jars_experimental'),
    ]

    operations = [
        migrations.AddField(
            model_name='jars',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
