# Generated by Django 5.0.4 on 2024-04-30 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_jars_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jars',
            name='file_size',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
