# Generated by Django 5.0.4 on 2024-04-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_jars_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jars',
            name='file_size',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
