# Generated by Django 5.0.4 on 2024-04-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_rename_jars_jar'),
    ]

    operations = [
        migrations.AddField(
            model_name='jar',
            name='file_hash',
            field=models.CharField(editable=False, max_length=70, null=True),
        ),
    ]
