# Generated by Django 5.0.6 on 2024-05-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_jar_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jar',
            name='buildnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jar',
            name='file_hash',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jar',
            name='software',
            field=models.CharField(choices=[('Vanilla', 'Vanilla'), ('Paper', 'Paper'), ('Purpur', 'Purpur'), ('Purformance', 'Purformance'), ('Spigot', 'Spigot'), ('CraftBukkit', 'CraftBukkit'), ('Tuinity', 'Tuinity'), ('Airplane', 'Airplane'), ('Folia', 'Folia'), ('SpongeVanilla', 'SpongeVanilla'), ('Glowstone', 'Glowstone'), ('Fabric', 'Fabric'), ('Forge', 'Forge'), ('Crucible', 'Crucible'), ('Cardboard', 'Cardboard'), ('Arclight', 'Arclight'), ('Mohist', 'Mohist'), ('Magma', 'Magma'), ('SpongeForge', 'SpongeForge'), ('Waterfall', 'Waterfall'), ('Velocity', 'Velocity'), ('Bungeecord', 'Bungeecord'), ('Travertine', 'Travertine')], max_length=50),
        ),
    ]
