# Generated by Django 5.0.6 on 2024-05-16 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_jar_buildnum_alter_jar_file_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jar',
            old_name='type',
            new_name='project',
        ),
    ]
